In [ ]:
#imports
import pandas as pd
#import: disponibiliza a biblioteca no nosso código.
#pandas: nome da biblioteca.
#pd: apelido que usaremos para escrever menos.

In [6]:
#exemplo 1 - lendo de um dicionário 
# Esse dicionário tem três chaves. Cada chave vira uma coluna, 
# e cada lista contém os valores daquela coluna. 

dados = {
    "nome": ["Ana", "Bruno", "Carla", "Diego"],
    "nota": [8, 5, 9, 6],
    "faltas": [2, 5, 1, 3]
}

dados

{'nome': ['Ana', 'Bruno', 'Carla', 'Diego'],
 'nota': [8, 5, 9, 6],
 'faltas': [2, 5, 1, 3]}

In [5]:
# pd.DataFrame(dados) transforma esses dados em uma tabela. Guardamos a tabela na variável df.

df = pd.DataFrame(dados)

df

    nome  nota  faltas
0    Ana     8       2
1  Bruno     5       5
2  Carla     9       1
3  Diego     6       3

In [7]:
#visualizar as primeiras linhas
df.head(2)

    nome  nota  faltas
0    Ana     8       2
1  Bruno     5       5

In [8]:
#selecionar uma coluna
df["nota"]

0    8
1    5
2    9
3    6
Name: nota, dtype: int64

In [9]:
#calculo da média
#usando for
soma = 0
quantidade = 0
for nota in df["nota"]:
    soma += nota
    quantidade += 1

media = soma / quantidade
media

7.0

In [12]:
#outra opção para calcular a média
media_2 = df["nota"].mean()
print(media_2)

7.0

In [14]:
#alunos com nota acima da média
df_alunos_acima_media = df[df["nota"] > media_2]
df_alunos_acima_media

    nome  nota  faltas
0    Ana     8       2
2  Carla     9       1

In [17]:
#alunos com nota acima da média
df_alunos_acima_media = df[(df["nota"] > media_2) | (df["faltas"] == 0)]
df_alunos_acima_media

    nome  nota  faltas
0    Ana     8       2
2  Carla     9       1

In [18]:
#alunos com nota acima da média
df_alunos_acima_media = df[(df["nota"] > media_2) & (df["faltas"] == 0)]
df_alunos_acima_media

Empty DataFrame
Columns: [nome, nota, faltas]
Index: []

0      Ana
2    Carla
Name: nome, dtype: object

Comando	-> Como escolhemos os dados
loc	 -> Pelos nomes das colunas, rótulos das linhas ou condições
iloc -> Pela posição das linhas e colunas na tabela

In [ ]:
#Na tabela df, selecione as linhas com nota maior ou igual a 7 e mostre somente a coluna nome.”
names = df.loc[df["nota"] > 7, "nome"]
names

0      Ana
2    Carla
Name: nome, dtype: object

In [ ]:
#Queremos as duas primeiras linhas e as duas primeiras colunas:
df.iloc[:2, :2]
#Antes da vírgula, 0:2: seleciona as linhas nas posições 0 e 1.
#Depois da vírgula, 0:2: seleciona as colunas nas posições 0 e 1.

    nome  nota
0    Ana     8
1  Bruno     5

In [ ]:
#Selecionar todas as linhas e uma coluna
df.loc[:, "nome"]
# O ':' sozinho significa todas as linhas.

0      Ana
1    Bruno
2    Carla
3    Diego
Name: nome, dtype: object